#optional file
#custom port (to deploy it to AWS EC2 it has to run to port 5000 and EC2 is running on this port)
server:
  port: 5000

#spring:
#  thymeleaf:
#    cache: false

#NOT wrking logging:
#  level:
#    root: WARN
#      org.springframework.security: DEBUG

#Mark active profile
spring:
    profiles:
      active: development
# for PROD in aws add env variable -Dspring.profiles.active=production
#You can also create yml file / profile e.g. application-production.yml
# triple hyphens acts as a divider between the profiles e.g.

#---
#spring:
#profiles: development

#logging:
#  level:
#    root: DEBUG
#---


lbl:
  myNameIs: Amar Pandav

